-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 13, 2019 at 03:29 PM
-- Server version: 10.1.38-MariaDB
-- PHP Version: 7.3.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `myshopdb`
--

-- --------------------------------------------------------

--
-- Table structure for table `cart`
--

CREATE TABLE `cart` (
  `email` varchar(50) NOT NULL,
  `pone` varchar(50) NOT NULL,
  `ptwo` varchar(50) NOT NULL,
  `pthree` varchar(50) NOT NULL,
  `pfour` varchar(50) NOT NULL,
  `pfive` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `cart`
--

INSERT INTO `cart` (`email`, `pone`, `ptwo`, `pthree`, `pfour`, `pfive`) VALUES
('mayankkhurmai8@gmail.com', 'a1', 'a2', '', '', '');

-- --------------------------------------------------------

--
-- Table structure for table `contact`
--

CREATE TABLE `contact` (
  `cname` varchar(50) NOT NULL,
  `cemail` varchar(50) NOT NULL,
  `cmobile` bigint(15) NOT NULL,
  `csubject` varchar(200) NOT NULL,
  `ctext` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `contact`
--

INSERT INTO `contact` (`cname`, `cemail`, `cmobile`, `csubject`, `ctext`) VALUES
('Mayank', 'mayankkhurmai8@gmail.com', 9720315564, 'Complaint About Product', 'Hello World');

-- --------------------------------------------------------

--
-- Table structure for table `logininfo`
--

CREATE TABLE `logininfo` (
  `uname` varchar(50) NOT NULL,
  `emailadd` varchar(50) NOT NULL,
  `mobileno` bigint(15) NOT NULL,
  `location` varchar(50) NOT NULL,
  `pass` varchar(50) NOT NULL,
  `hashpass` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `logininfo`
--

INSERT INTO `logininfo` (`uname`, `emailadd`, `mobileno`, `location`, `pass`, `hashpass`) VALUES
('Mayank Khurmai', 'mayankkhurmai8@gmail.com', 9720315564, 'Uttar Pradesh', 'khurmai', 'e901b88c0198ad207849972cbf1e7cb3'),
('Pragati Singh', 'pragati@gmail.com', 7905529488, 'Delhi', 'singh', '2865a5b14e5a70273a7d311bfc150f4f'),
('Pranjul', 'pranjul41199@gmai.com', 6386445655, 'Uttar Pradesh', '6789', '46d045ff5190f6ea93739da6c0aa19bc');

-- --------------------------------------------------------

--
-- Table structure for table `productinfo`
--

CREATE TABLE `productinfo` (
  `pid` varchar(10) NOT NULL,
  `pname` varchar(100) NOT NULL,
  `pmrp` float NOT NULL,
  `pprice` float NOT NULL,
  `psave` float NOT NULL,
  `pavailable` varchar(50) NOT NULL,
  `pla` varchar(300) NOT NULL,
  `plb` varchar(300) NOT NULL,
  `plc` varchar(300) NOT NULL,
  `pld` varchar(300) NOT NULL,
  `ple` varchar(300) NOT NULL,
  `pdesc` varchar(1000) NOT NULL,
  `pimgadd` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `productinfo`
--

INSERT INTO `productinfo` (`pid`, `pname`, `pmrp`, `pprice`, `psave`, `pavailable`, `pla`, `plb`, `plc`, `pld`, `ple`, `pdesc`, `pimgadd`) VALUES
('a1', 'Dennis Men\'s Shirt', 980, 670, 310, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/a1.jpeg'),
('a2', 'Streats Men\'s Regular', 710, 160, 550, 'Currently Available', 'Available in all the Sizes', 'Purely Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. .', 'images/a2.jpeg'),
('a3', 'Lion\'s Roar Shirt', 1180, 770, 410, 'Currently Unavailable', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/a3.jpeg'),
('a4', 'Dennim Blue', 1340, 790, 550, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/a4.jpeg'),
('a5', 'Lingo Mens\'s cotton', 680, 470, 210, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/a5.jpeg'),
('a6', 'Campus Stura Men\'s', 680, 470, 210, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/a6.jpeg'),
('b1', 'Quirky T-Shirt', 980, 670, 310, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/b1.jpeg'),
('b2', 'Nighty Kurti', 710, 160, 550, 'Currently Available', 'Available in all the Sizes', 'Purely Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. .', 'images/b2.jpeg'),
('b3', 'Elvis Crop', 1180, 770, 410, 'Currently Unavailable', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/b3.jpeg'),
('b4', 'Party Frok', 1340, 790, 550, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/b4.jpeg'),
('b5', 'Style Villi T-shirt', 680, 470, 210, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/b5.jpeg'),
('b6', 'Party Fashion Gown', 680, 470, 210, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/b5.jpeg'),
('c1', 'Kids Vockey-Tockey', 980, 670, 310, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/c1.jpeg'),
('c2', 'Hfid Speaker', 710, 160, 550, 'Currently Available', 'Available in all the Sizes', 'Purely Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. .', 'images/c2.jpeg'),
('c3', '2-USB Speaker', 1180, 770, 410, 'Currently Unavailable', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/a3.jpeg'),
('c4', 'Resberi Pi', 1340, 790, 550, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/c4.jpeg'),
('c5', 'Mobile Stand', 680, 470, 210, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/c5.jpeg'),
('c6', 'USB Hardisk', 680, 470, 210, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/c6.jpeg'),
('d1', 'Android Galaxy', 980, 670, 310, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/d1.jpeg'),
('d2', 'Touchscreen Android', 710, 160, 550, 'Currently Available', 'Available in all the Sizes', 'Purely Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. .', 'images/d2.jpeg'),
('d3', 'Samsung Galaxy', 1180, 770, 410, 'Currently Unavailable', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/d3.jpeg'),
('d4', 'Vivo Triple V9', 1340, 790, 550, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/d4.jpeg'),
('d5', 'Motorola Green', 680, 470, 210, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/d5.jpeg'),
('d6', 'Panasonic Multi', 680, 470, 210, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/d6.jpeg'),
('e1', 'Handball', 980, 670, 310, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/e1.jpeg'),
('e2', 'Baseball And Softball', 710, 160, 550, 'Currently Available', 'Available in all the Sizes', 'Purely Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. .', 'images/e2.jpeg'),
('e3', 'Gym Running', 1180, 770, 410, 'Currently Unavailable', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/e3.jpeg'),
('e4', 'Cricket Bat', 1340, 790, 550, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/e4.jpeg'),
('e5', 'Cricket kit', 680, 470, 210, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/e5.jpeg'),
('e6', 'Badminton Set', 680, 470, 210, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/e6.jpeg'),
('f1', 'Study Table', 980, 670, 310, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/f1.jpeg'),
('f2', 'Dinning Table', 710, 160, 550, 'Currently Available', 'Available in all the Sizes', 'Purely Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. .', 'images/f2.jpeg'),
('f3', 'Lion\'s Roar Shirt', 1180, 770, 410, 'Currently Unavailable', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/f3.jpeg'),
('f4', 'Dennim Blue', 1340, 790, 550, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/f4.jpeg'),
('f5', 'Lingo Mens\'s cotton', 680, 470, 210, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/f5.jpeg'),
('f6', 'Lingo Mens\'s cotton', 680, 470, 210, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/f6.jpeg'),
('g1', 'Quirky T-Shirt', 980, 670, 310, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/g1.jpeg'),
('g2', 'Streats Men\'s Regular', 710, 160, 550, 'Currently Available', 'Available in all the Sizes', 'Purely Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. .', 'images/g2.jpeg'),
('g3', 'Lion\'s Roar Shirt', 1180, 770, 410, 'Currently Unavailable', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/g3.jpeg'),
('g4', 'Dennim Blue', 1340, 790, 550, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/g4.jpeg'),
('g5', 'Lingo Mens\'s cotton', 680, 470, 210, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/g5.jpeg'),
('g6', 'Lingo Mens\'s cotton', 680, 470, 210, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/g6.jpeg'),
('h1', 'Dennis Men\'s Shirt', 980, 670, 310, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/h1.jpeg');
INSERT INTO `productinfo` (`pid`, `pname`, `pmrp`, `pprice`, `psave`, `pavailable`, `pla`, `plb`, `plc`, `pld`, `ple`, `pdesc`, `pimgadd`) VALUES
('h2', 'Streats Men\'s Regular', 710, 160, 550, 'Currently Available', 'Available in all the Sizes', 'Purely Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. .', 'images/h2.jpeg'),
('h3', 'Lion\'s Roar Shirt', 1180, 770, 410, 'Currently Unavailable', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/h3.jpeg'),
('h4', 'Dennim Blue', 1340, 790, 550, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/h4.jpeg'),
('h5', 'Lingo Mens\'s cotton', 680, 470, 210, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/h5.jpeg'),
('h6', 'Lingo Mens\'s cotton', 680, 470, 210, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/h6.jpeg'),
('i1', 'Quirky T-Shirt', 980, 670, 310, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/i1.jpeg'),
('i2', 'Streats Men\'s Regular', 710, 160, 550, 'Currently Available', 'Available in all the Sizes', 'Purely Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. .', 'images/i2.jpeg'),
('i3', 'Lion\'s Roar Shirt', 1180, 770, 410, 'Currently Unavailable', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/i3.jpeg'),
('i4', 'Dennim Blue', 1340, 790, 550, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/i4.jpeg'),
('i5', 'Lingo Mens\'s cotton', 680, 470, 210, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/i5.jpeg'),
('i6', 'Lingo Mens\'s cotton', 680, 470, 210, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/i6.jpeg'),
('j1', 'Dennis Men\'s Shirt', 980, 670, 310, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/j1.jpeg'),
('j2', 'Streats Men\'s Regular', 710, 160, 550, 'Currently Available', 'Available in all the Sizes', 'Purely Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. .', 'images/j2.jpeg'),
('j3', 'Lion\'s Roar Shirt', 1180, 770, 410, 'Currently Unavailable', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/j3.jpeg'),
('j4', 'Dennim Blue', 1340, 790, 550, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/j4.jpeg'),
('j5', 'Lingo Mens\'s cotton', 680, 470, 210, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/j5.jpeg'),
('j6', 'Lingo Mens\'s cotton', 680, 470, 210, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/j6.jpeg'),
('k1', 'Quirky T-Shirt', 980, 670, 310, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/k1.jpeg'),
('k2', 'Streats Men\'s Regular', 710, 160, 550, 'Currently Available', 'Available in all the Sizes', 'Purely Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. .', 'images/k2.jpeg'),
('k3', 'Lion\'s Roar Shirt', 1180, 770, 410, 'Currently Unavailable', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/k3.jpeg'),
('k4', 'Dennim Blue', 1340, 790, 550, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/k4.jpeg'),
('k5', 'Lingo Mens\'s cotton', 680, 470, 210, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/k5.jpeg'),
('k6', 'Lingo Mens\'s cotton', 680, 470, 210, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/k6.jpeg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `cart`
--
ALTER TABLE `cart`
  ADD PRIMARY KEY (`email`);

--
-- Indexes for table `contact`
--
ALTER TABLE `contact`
  ADD PRIMARY KEY (`cemail`);

--
-- Indexes for table `logininfo`
--
ALTER TABLE `logininfo`
  ADD PRIMARY KEY (`emailadd`);

--
-- Indexes for table `productinfo`
--
ALTER TABLE `productinfo`
  ADD PRIMARY KEY (`pid`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
