-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 14, 2019 at 12:44 PM
-- Server version: 10.1.38-MariaDB
-- PHP Version: 7.3.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `myshopdb`
--

-- --------------------------------------------------------

--
-- Table structure for table `carttable`
--

CREATE TABLE `carttable` (
  `emailadd` varchar(50) NOT NULL,
  `pone` varchar(50) NOT NULL,
  `ppone` int(5) NOT NULL,
  `ptwo` varchar(50) NOT NULL,
  `pptwo` int(5) NOT NULL,
  `pthree` varchar(50) NOT NULL,
  `ppthree` int(5) NOT NULL,
  `pfour` varchar(50) NOT NULL,
  `ppfour` int(5) NOT NULL,
  `pfive` varchar(50) NOT NULL,
  `ppfive` int(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `carttable`
--

INSERT INTO `carttable` (`emailadd`, `pone`, `ppone`, `ptwo`, `pptwo`, `pthree`, `ppthree`, `pfour`, `ppfour`, `pfive`, `ppfive`) VALUES
('mayankk@gmail.com', 'Vivo Triple V9', 18500, 'Kingston Speaker', 1200, '', 0, '', 0, '', 0),
('pragati@gmail.com', 'Motorola Green', 36500, 'Handball', 670, 'Quirky T-Shirt', 400, '', 0, '', 0),
('pranjul41199@gmail.com', 'Elvis Crop', 620, 'Mobile Stand', 230, 'Cricket Bat', 500, 'Bharat Safe', 7000, 'Adidas Black', 2200),
('priyasharma@gmail.com', '2-USB Speaker', 640, ' ', 0, ' ', 0, ' ', 0, ' ', 0);

-- --------------------------------------------------------

--
-- Table structure for table `contact`
--

CREATE TABLE `contact` (
  `cname` varchar(50) NOT NULL,
  `cemail` varchar(50) NOT NULL,
  `cmobile` bigint(15) NOT NULL,
  `csubject` varchar(200) NOT NULL,
  `ctext` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `contact`
--

INSERT INTO `contact` (`cname`, `cemail`, `cmobile`, `csubject`, `ctext`) VALUES
('Mayank', 'mayankkhurmai8@gmail.com', 9720315564, 'Complaint About Product', 'Hello World');

-- --------------------------------------------------------

--
-- Table structure for table `logininfo`
--

CREATE TABLE `logininfo` (
  `uname` varchar(50) NOT NULL,
  `emailadd` varchar(50) NOT NULL,
  `mobileno` bigint(15) NOT NULL,
  `location` varchar(50) NOT NULL,
  `pass` varchar(50) NOT NULL,
  `hashpass` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `logininfo`
--

INSERT INTO `logininfo` (`uname`, `emailadd`, `mobileno`, `location`, `pass`, `hashpass`) VALUES
('Mayank', 'mayankk@gmail.com', 9720315564, 'Uttar Pradesh', 'khurmai', 'e901b88c0198ad207849972cbf1e7cb3'),
('Pragati', 'pragati@gmail.com', 7905529488, 'Delhi', 'singh', '2865a5b14e5a70273a7d311bfc150f4f'),
('Pranjul', 'pranjul41199@gmail.com', 6386445655, 'Uttar Pradesh', '6789', '46d045ff5190f6ea93739da6c0aa19bc'),
('Topper', 'priyasharma@gmail.com', 9027420436, 'Uttar Pradesh', 'mayank', '308a3820e4cccbe043cb5228de5e71e3');

-- --------------------------------------------------------

--
-- Table structure for table `productinfo`
--

CREATE TABLE `productinfo` (
  `pid` varchar(10) NOT NULL,
  `pname` varchar(100) NOT NULL,
  `pmrp` float NOT NULL,
  `pprice` float NOT NULL,
  `psave` float NOT NULL,
  `off` int(5) NOT NULL,
  `pavailable` varchar(50) NOT NULL,
  `pla` varchar(300) NOT NULL,
  `plb` varchar(300) NOT NULL,
  `plc` varchar(300) NOT NULL,
  `pld` varchar(300) NOT NULL,
  `ple` varchar(300) NOT NULL,
  `pdesc` varchar(1000) NOT NULL,
  `pimgadd` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `productinfo`
--

INSERT INTO `productinfo` (`pid`, `pname`, `pmrp`, `pprice`, `psave`, `off`, `pavailable`, `pla`, `plb`, `plc`, `pld`, `ple`, `pdesc`, `pimgadd`) VALUES
('a1', 'Dennis Men\'s Shirt', 980, 670, 310, 32, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/a1.jpeg'),
('a2', 'Streats Men\'s Regular', 710, 550, 160, 22, 'Currently Available', 'Available in all the Sizes', 'Purely Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. .', 'images/a2.jpeg'),
('a3', 'Lion\'s Roar Shirt', 1180, 770, 410, 35, 'Currently Unavailable', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/a3.jpeg'),
('a4', 'Dennim Blue', 1340, 790, 550, 42, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/a4.jpeg'),
('a5', 'Lingo Mens\'s cotton', 680, 470, 210, 30, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/a5.jpeg'),
('a6', 'Campus Stura Men\'s', 600, 540, 60, 10, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/a6.jpeg'),
('b1', 'Quirky T-Shirt', 780, 400, 380, 50, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/b1.jpeg'),
('b2', 'Nighty Kurti', 1100, 550, 550, 50, 'Currently Available', 'Available in all the Sizes', 'Purely Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. .', 'images/b2.jpeg'),
('b3', 'Elvis Crop', 1180, 620, 560, 48, 'Currently Unavailable', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/b3.jpeg'),
('b4', 'Party Frok', 650, 450, 200, 30, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/b4.jpeg'),
('b5', 'Style Villi T-shirt', 960, 770, 190, 20, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/b5.jpeg'),
('b6', 'Party Fashion Gown', 1280, 1070, 210, 17, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/b5.jpeg'),
('c1', 'Kids Vockey-Tockey', 1500, 1000, 500, 35, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/c1.jpeg'),
('c2', 'Hfid Speaker', 2180, 1750, 430, 20, 'Currently Available', 'Available in all the Sizes', 'Purely Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. .', 'images/c2.jpeg'),
('c3', '2-USB Speaker', 970, 640, 330, 35, 'Currently Unavailable', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/c3.jpeg'),
('c4', 'Resberi Pi', 1380, 1200, 180, 14, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/c4.jpeg'),
('c5', 'Mobile Stand', 480, 230, 250, 53, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/c5.jpeg'),
('c6', 'USB Hardisk', 1980, 1770, 210, 10, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/c6.jpeg'),
('d1', 'Android Galaxy', 19800, 16700, 3100, 15, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/d1.jpeg'),
('d2', 'Touchscreen Android', 13800, 12700, 1100, 8, 'Currently Available', 'Available in all the Sizes', 'Purely Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. .', 'images/d2.jpeg'),
('d3', 'Samsung Galaxy', 28800, 26700, 2100, 10, 'Currently Unavailable', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/d3.jpeg'),
('d4', 'Vivo Triple V9', 21900, 18500, 3400, 15, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/d4.jpeg'),
('d5', 'Motorola Green', 37900, 36500, 1400, 5, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/d5.jpeg'),
('d6', 'Panasonic Multi', 15800, 12700, 2100, 20, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/d6.jpeg'),
('e1', 'Handball', 1340, 670, 670, 50, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/e1.jpeg'),
('e2', 'Baseball And Softball', 980, 570, 410, 48, 'Currently Available', 'Available in all the Sizes', 'Purely Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. .', 'images/e2.jpeg'),
('e3', 'Gym Running', 9100, 8000, 1100, 13, 'Currently Unavailable', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/e3.jpeg'),
('e4', 'Cricket Bat', 1000, 500, 500, 50, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/e4.jpeg'),
('e5', 'Cricket kit', 2300, 2000, 300, 15, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/e5.jpeg'),
('e6', 'Badminton Set', 980, 750, 230, 25, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/e6.jpeg'),
('f1', 'Study Table', 2800, 2700, 100, 5, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/f1.jpeg'),
('f2', 'Dinning Table', 6880, 6000, 880, 13, 'Currently Available', 'Available in all the Sizes', 'Purely Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. .', 'images/f2.jpeg'),
('f3', 'Soft Sofa', 2900, 2700, 200, 7, 'Currently Unavailable', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/f3.jpeg'),
('f4', 'Vertical Table', 800, 700, 100, 12, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/f4.jpeg'),
('f5', 'Bharat Safe', 7500, 7000, 500, 8, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/f5.jpeg'),
('f6', 'Double Bed', 9700, 8500, 1200, 13, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/f6.jpeg'),
('g1', 'Boys White Shoes', 900, 600, 300, 32, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/g1.jpeg'),
('g2', 'Desnis Black Shoes', 1450, 1300, 150, 10, 'Currently Available', 'Available in all the Sizes', 'Purely Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. .', 'images/g2.jpeg'),
('g3', 'Adidas Shoes', 2750, 2400, 350, 13, 'Currently Unavailable', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/g3.jpeg'),
('g4', 'Adidas Black', 2300, 2200, 100, 5, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/g4.jpeg'),
('g5', 'Gradient Shoes', 2000, 1100, 900, 45, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/g5.jpeg'),
('g6', 'Multi Color Shoes', 900, 700, 200, 22, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/g6.jpeg');
INSERT INTO `productinfo` (`pid`, `pname`, `pmrp`, `pprice`, `psave`, `off`, `pavailable`, `pla`, `plb`, `plc`, `pld`, `ple`, `pdesc`, `pimgadd`) VALUES
('h1', 'Redlix Watch', 2200, 2000, 200, 10, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/h1.jpeg'),
('h2', 'Wrist Watch', 1980, 1700, 280, 15, 'Currently Available', 'Available in all the Sizes', 'Purely Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. .', 'images/h2.jpeg'),
('h3', 'Multi Shade Watch', 1580, 1470, 110, 7, 'Currently Unavailable', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/h3.jpeg'),
('h4', 'Wodden Style Watch', 1500, 800, 700, 47, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/h4.jpeg'),
('h5', 'Golden Watch', 1200, 1000, 200, 17, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/h5.jpeg'),
('h6', 'Proffesional Watch', 1500, 1400, 100, 7, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/h6.jpeg'),
('i1', 'Plastic Mug-Plate', 2300, 1300, 1000, 45, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/i1.jpeg'),
('i2', 'Cup-Plate Set', 390, 300, 90, 25, 'Currently Available', 'Available in all the Sizes', 'Purely Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. .', 'images/i2.jpeg'),
('i3', 'Plastic Boxes', 850, 500, 350, 40, 'Currently Unavailable', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/i3.jpeg'),
('i4', 'Tea Cup', 330, 150, 180, 55, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/i4.jpeg'),
('i5', 'Blue Plate Set', 700, 550, 150, 22, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/i5.jpeg'),
('i6', 'Wine Glass', 240, 200, 40, 17, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/i6.jpeg'),
('j1', 'Head &amp Soulder', 180, 90, 90, 50, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/j1.jpeg'),
('j2', 'Dove Shampoo', 240, 120, 120, 50, 'Currently Available', 'Available in all the Sizes', 'Purely Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. .', 'images/j2.jpeg'),
('j3', 'Herbal Facewash', 400, 250, 150, 40, 'Currently Unavailable', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/j3.jpeg'),
('j4', 'Hair Fall Shampoo', 410, 320, 90, 22, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/j4.jpeg'),
('j5', 'Indulekha', 500, 350, 150, 30, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/j5.jpeg'),
('j6', 'Wow Shampoo', 280, 220, 60, 22, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/j6.jpeg'),
('k1', 'Boss Speakers', 2400, 2300, 100, 5, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/k1.jpeg'),
('k2', 'Home Theatre', 1500, 1350, 150, 10, 'Currently Available', 'Available in all the Sizes', 'Purely Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. .', 'images/k2.jpeg'),
('k3', 'Amazon Alexa', 7200, 6000, 1200, 17, 'Currently Unavailable', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/k3.jpeg'),
('k4', 'Sony Speakers', 2800, 2500, 300, 10, 'Currently Available', 'Available in all the Sizes', 'Pure Cotton Shirt', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/k4.jpeg'),
('k5', 'Kingston Speaker', 1380, 1200, 180, 15, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/k5.jpeg'),
('k6', 'Home Speakers', 1150, 1000, 150, 15, 'Currently Available', 'Pure Cotton Shirt', 'Available in all the Sizes', 'Fashionable Shirt', 'Available in the Black, Blue, Red and Orange Colour', 'Attractive Western Design', 'New Tide Plus with extra power detergent, now with the added power of bar, has been developed to bring you brilliant whiteness on your clothes. It removes dirt even from washed clothes to give you even better cleaning. The enzyme formula in the washing powder helps in washing away the toughest stains on the clothes, thus making them look bright and fresh. Kids often soil their clothes, especially school uniforms, with tough-to-remove stains and dirt. Tide Plus with extra power is a fine detergent powder which dissolves easily in water and quickly generates foam. The superior formulation can remove dirt even from difficult-to-clean areas like collars and cuffs and leaves behind a wonderful fragrance. The product works on both white and colored clothes. Extra power refers to vs previous Tide Plus. Tide, a unit of procter and gamble, is the world’s oldest and most trusted detergent brand and is the market leader in 23 countries around the world.', 'images/k6.jpeg');

--
-- Indexes for dumped tables
--
#btn{
    width: 50%;
    height: auto;
    margin: 0 auto;
    } ffj
    gvv
.btn-size{
    width: 100%;
    heigjsh
    hehehht: 100px;
    margin: 5px;
    border-width: 2px;
    background-color: aquamarine;
    border-radius: 5px;
    font-weight: bold;
    font-size: 15px;
    border-style: outset;
    }
--
-- Indexes for table `carttable`
--
ALTER TABLE `carttable`
  ADD PRIMARY KEY (`emailadd`);

--
-- Indexes for table `contact`
--
ALTER TABLE `contact`
  ADD PRIMARY KEY (`cemail`);

--
-- Indexes for table `logininfo`
--
ALTER TABLE `logininfo`
  ADD PRIMARY KEY (`emailadd`);

--
-- Indexes for table `productinfo`
--
ALTER TABLE `productinfo`
  ADD PRIMARY KEY (`pid`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
